import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { analyzeRepo } from "../src/analyzer";
import { generateSkill, scoreSkillQuality } from "../src/generator";

function makeTmpDir(): string {
  const dir = path.join(os.tmpdir(), `repo2skill-test-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`);
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function writeFile(dir: string, relPath: string, content: string) {
  const full = path.join(dir, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
}

describe("generateSkill — Node.js project", () => {
  let repoDir: string;
  let outDir: string;
  let skillMd: string;

  beforeEach(async () => {
    repoDir = makeTmpDir();
    outDir = makeTmpDir();
    writeFile(repoDir, "package.json", JSON.stringify({
      name: "test-lib",
      description: "A test library for unit testing",
      license: "MIT",
      bin: { "test-lib": "./dist/cli.js" },
      dependencies: { commander: "^12.0.0" },
    }));
    writeFile(repoDir, "README.md", [
      "# test-lib",
      "",
      "A test library for unit testing.",
      "",
      "## Installation",
      "",
      "```bash",
      "npm install test-lib",
      "```",
      "",
      "## Usage",
      "",
      "```js",
      'const tl = require("test-lib");',
      "tl.run();",
      "```",
      "",
      "## Features",
      "",
      "- Lightning fast execution engine",
      "- Zero configuration needed for setup",
      "- Extensible plugin system built in",
      "",
      "## Examples",
      "",
      "```js",
      "tl.advanced();",
      "```",
    ].join("\n"));
    writeFile(repoDir, "src/index.ts", "export function run() {}");
    writeFile(repoDir, "tests/index.test.ts", "");

    const analysis = await analyzeRepo(repoDir, "test-lib");
    const skillDir = path.join(outDir, "test-lib");
    generateSkill(analysis, skillDir, "test-lib", "https://github.com/test/test-lib");
    skillMd = fs.readFileSync(path.join(skillDir, "SKILL.md"), "utf-8");
  });

  afterEach(() => {
    fs.rmSync(repoDir, { recursive: true, force: true });
    fs.rmSync(outDir, { recursive: true, force: true });
  });

  it("contains skill name in frontmatter", () => {
    expect(skillMd).toContain("name: test-lib");
  });

  it("contains install command", () => {
    expect(skillMd).toContain("npm install test-lib");
  });

  it('contains "When to Use" section', () => {
    expect(skillMd).toContain("## When to Use");
  });

  it('contains "Examples" or usage section', () => {
    expect(skillMd.includes("## Examples") || skillMd.includes("### Basic Usage")).toBe(true);
  });

  it("features are populated", () => {
    expect(skillMd).toContain("Key Features");
    expect(skillMd).toContain("Lightning fast");
  });

  it("license detected", () => {
    expect(skillMd).toContain("MIT");
  });

  it("source_repo in frontmatter", () => {
    expect(skillMd).toContain("source_repo: https://github.com/test/test-lib");
  });

  it("generated by badge at the end", () => {
    expect(skillMd).toContain("Generated by [repo2skill]");
  });
});

describe("generateSkill — Python project", () => {
  let repoDir: string;
  let outDir: string;
  let skillMd: string;

  beforeEach(async () => {
    repoDir = makeTmpDir();
    outDir = makeTmpDir();
    writeFile(repoDir, "pyproject.toml", `[project]\nname = "pylib"\ndescription = "A Python library"\n`);
    writeFile(repoDir, "README.md", "# pylib\n\nA Python library for data processing.\n\n## Usage\n\n```python\nimport pylib\npylib.process()\n```\n");
    writeFile(repoDir, "pylib/__init__.py", "");

    const analysis = await analyzeRepo(repoDir, "pylib");
    const skillDir = path.join(outDir, "pylib");
    generateSkill(analysis, skillDir, "pylib");
    skillMd = fs.readFileSync(path.join(skillDir, "SKILL.md"), "utf-8");
  });

  afterEach(() => {
    fs.rmSync(repoDir, { recursive: true, force: true });
    fs.rmSync(outDir, { recursive: true, force: true });
  });

  it("generates SKILL.md for Python project", () => {
    expect(skillMd).toContain("name: pylib");
  });

  it("contains pip install command", () => {
    expect(skillMd).toContain("pip install pylib");
  });

  it("detects Python language", () => {
    expect(skillMd).toContain("Python");
  });
});

describe("generateSkill — edge cases", () => {
  let repoDir: string;
  let outDir: string;

  beforeEach(() => {
    repoDir = makeTmpDir();
    outDir = makeTmpDir();
  });
  afterEach(() => {
    fs.rmSync(repoDir, { recursive: true, force: true });
    fs.rmSync(outDir, { recursive: true, force: true });
  });

  it("handles missing README gracefully", async () => {
    writeFile(repoDir, "package.json", JSON.stringify({ name: "no-readme", description: "No readme here" }));
    writeFile(repoDir, "index.js", "");
    const analysis = await analyzeRepo(repoDir, "no-readme");
    const skillDir = path.join(outDir, "no-readme");
    generateSkill(analysis, skillDir, "no-readme");
    const md = fs.readFileSync(path.join(skillDir, "SKILL.md"), "utf-8");
    expect(md).toContain("name: no-readme");
    expect(md).toContain("No readme here");
  });

  it("no HTTP false positives for non-HTTP projects", async () => {
    writeFile(repoDir, "package.json", JSON.stringify({ name: "math-lib", description: "A math library for computations" }));
    writeFile(repoDir, "README.md", "# math-lib\n\nA math library for computations.\n");
    writeFile(repoDir, "index.js", "");
    const analysis = await analyzeRepo(repoDir, "math-lib");
    const skillDir = path.join(outDir, "math-lib");
    generateSkill(analysis, skillDir, "math-lib");
    const md = fs.readFileSync(path.join(skillDir, "SKILL.md"), "utf-8");
    expect(md).not.toContain("Make HTTP requests");
  });

  it("creates references directory for large README", async () => {
    const longReadme = "# Big\n\n" + "Lorem ipsum dolor sit amet. ".repeat(100);
    writeFile(repoDir, "README.md", longReadme);
    writeFile(repoDir, "index.js", "");
    const analysis = await analyzeRepo(repoDir, "big");
    const skillDir = path.join(outDir, "big");
    const result = generateSkill(analysis, skillDir, "big");
    expect(result.referencesCount).toBeGreaterThan(0);
    expect(fs.existsSync(path.join(skillDir, "references", "README.md"))).toBe(true);
  });
});

describe("scoreSkillQuality", () => {
  it("scores high for complete analysis", async () => {
    const repoDir = makeTmpDir();
    writeFile(repoDir, "package.json", JSON.stringify({ name: "q", description: "Quality test", license: "MIT" }));
    writeFile(repoDir, "README.md", "# Q\n\nQuality test.\n\n## Installation\n\n```bash\nnpm i q\n```\n\n## Features\n\n- Fast\n- Simple\n- Reliable\n");
    writeFile(repoDir, "index.js", "");
    const analysis = await analyzeRepo(repoDir, "q");
    const q = scoreSkillQuality(analysis);
    expect(q.score).toBeGreaterThanOrEqual(30);
    expect(q.details.find((d: any) => d.label === "Has description")!.pass).toBe(true);
    fs.rmSync(repoDir, { recursive: true, force: true });
  });

  it("scores low for minimal analysis", async () => {
    const repoDir = makeTmpDir();
    writeFile(repoDir, "main.c", "int main() { return 0; }");
    const analysis = await analyzeRepo(repoDir, "minimal");
    const q = scoreSkillQuality(analysis);
    expect(q.score).toBeLessThanOrEqual(30);
    fs.rmSync(repoDir, { recursive: true, force: true });
  });
});
