import { describe, it, expect } from "vitest";
import { generateVersionStamp, formatVersionLine, injectVersionInfo, VersionInfo } from "../versioning";

const sampleInfo: VersionInfo = {
  tag: "v2.0.0",
  commit: "abc1234567890",
  commitShort: "abc1234",
  date: "2024-01-15",
  message: "Release v2.0.0",
};

describe("generateVersionStamp", () => {
  it("generates stamp with tag", () => {
    const stamp = generateVersionStamp(sampleInfo);
    expect(stamp).toContain('version_tag: "v2.0.0"');
    expect(stamp).toContain('version_commit: "abc1234"');
    expect(stamp).toContain('version_date: "2024-01-15"');
  });

  it("generates stamp without tag", () => {
    const info: VersionInfo = { ...sampleInfo, tag: undefined };
    const stamp = generateVersionStamp(info);
    expect(stamp).not.toContain("version_tag");
    expect(stamp).toContain('version_commit: "abc1234"');
  });
});

describe("formatVersionLine", () => {
  it("formats line with tag", () => {
    const line = formatVersionLine(sampleInfo);
    expect(line).toBe("> This skill was generated from v2.0.0 (commit abc1234)");
  });

  it("formats line without tag", () => {
    const info: VersionInfo = { ...sampleInfo, tag: undefined };
    const line = formatVersionLine(info);
    expect(line).toContain("commit abc1234");
    expect(line).toContain("2024-01-15");
  });
});

describe("injectVersionInfo", () => {
  it("injects into frontmatter and body", () => {
    const content = `---
name: test
description: A test skill
---

# test

> Generated by [repo2skill](https://github.com/NeuZhou/repo2skill)`;

    const result = injectVersionInfo(content, sampleInfo);
    expect(result).toContain('version_tag: "v2.0.0"');
    expect(result).toContain('version_commit: "abc1234"');
    expect(result).toContain("> This skill was generated from v2.0.0 (commit abc1234)");
    expect(result).toContain("> Generated by");
  });

  it("replaces existing version info", () => {
    const content = `---
name: test
version_tag: "v1.0.0"
version_commit: "old1234"
version_date: "2023-01-01"
---

# test

> This skill was generated from v1.0.0 (commit old1234)

> Generated by [repo2skill](https://github.com/NeuZhou/repo2skill)`;

    const result = injectVersionInfo(content, sampleInfo);
    expect(result).not.toContain("v1.0.0");
    expect(result).not.toContain("old1234");
    expect(result).toContain("v2.0.0");
    expect(result).toContain("abc1234");
  });
});
