import * as path from "path";
import * as fs from "fs";
import { RepoAnalysis } from "./analyzer";
import { Repo2SkillResult } from "./index";

export function generateSkill(
  analysis: RepoAnalysis,
  skillDir: string,
  skillName: string,
  sourceRepo?: string
): Repo2SkillResult {
  fs.mkdirSync(skillDir, { recursive: true });

  const isCLI = analysis.cliCommands.length > 0;
  const description = buildDescription(analysis, isCLI);
  const body = buildBody(analysis, skillName, isCLI);
  const generatedAt = new Date().toISOString();
  const repoLine = sourceRepo ? `\nsource_repo: ${sourceRepo}` : "";

  const skillMd = `---
name: ${skillName}
description: ${description}${repoLine}
generated_at: "${generatedAt}"
---

${body}

> Generated by [repo2skill](https://github.com/NeuZhou/repo2skill)`;

  fs.writeFileSync(path.join(skillDir, "SKILL.md"), skillMd);

  // References
  let referencesCount = 0;
  const refsDir = path.join(skillDir, "references");

  // API reference
  if (analysis.apiSection && analysis.apiSection.length > 200) {
    fs.mkdirSync(refsDir, { recursive: true });
    fs.writeFileSync(path.join(refsDir, "api.md"), `# API Reference — ${skillName}\n\n${analysis.apiSection}`);
    referencesCount++;
  }

  // Full README as reference
  if (analysis.readmeRaw.length > 1000) {
    fs.mkdirSync(refsDir, { recursive: true });
    fs.writeFileSync(path.join(refsDir, "README.md"), analysis.readmeRaw);
    referencesCount++;
  }

  return { skillDir, referencesCount };
}

function buildDescription(analysis: RepoAnalysis, isCLI: boolean): string {
  const parts: string[] = [];

  // Use rich description when available, otherwise core description
  const desc = analysis.richDescription || analysis.description || `${analysis.name} — a ${analysis.language} project.`;
  parts.push(desc.split("\n")[0].replace(/\n/g, " ").trim());

  // When to use (inline)
  if (analysis.whenToUse.length > 0) {
    parts.push(`WHEN: ${analysis.whenToUse.slice(0, 4).join(", ").toLowerCase()}.`);
  }

  // Trigger phrases
  if (analysis.triggerPhrases.length > 0) {
    parts.push(`Triggers: ${analysis.triggerPhrases.slice(0, 4).join(", ")}.`);
  }

  // Trim to reasonable length
  return parts.join(" ").slice(0, 500).replace(/"/g, '\\"');
}

function buildBody(analysis: RepoAnalysis, skillName: string, isCLI: boolean): string {
  const lines: string[] = [];

  lines.push(`# ${skillName}`);
  lines.push("");

  // Rich description
  if (analysis.richDescription) {
    lines.push(analysis.richDescription.split("\n")[0]);
    lines.push("");
  } else if (analysis.description) {
    lines.push(analysis.description.split("\n")[0]);
    lines.push("");
  }

  // When to Use / When NOT to Use
  lines.push("## When to Use");
  lines.push("");
  if (analysis.whenToUse.length > 0) {
    for (const item of analysis.whenToUse) {
      lines.push(`- ${item}`);
    }
  } else if (isCLI) {
    lines.push(`- Run \`${analysis.cliCommands[0]?.name || skillName}\` commands`);
  } else {
    lines.push(`- Work with the ${skillName} ${analysis.language} library`);
  }
  lines.push("");

  if (analysis.whenNotToUse.length > 0) {
    lines.push("## When NOT to Use");
    lines.push("");
    for (const item of analysis.whenNotToUse) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  // Quick Start (installation + basic usage combined)
  lines.push("## Quick Start");
  lines.push("");

  // Installation
  if (analysis.installInstructions) {
    const codeBlocks = extractCodeBlocks(analysis.installInstructions);
    if (codeBlocks.length > 0) {
      lines.push("### Install");
      lines.push("");
      lines.push(...codeBlocks.slice(0, 2).map(b => b));
      lines.push("");
    } else {
      lines.push("### Install");
      lines.push("");
      lines.push(trimSection(analysis.installInstructions, 10));
      lines.push("");
    }
  } else {
    lines.push("### Install");
    lines.push("");
    if (analysis.language === "JavaScript" || analysis.language === "TypeScript") {
      lines.push("```bash");
      lines.push(`npm install ${analysis.name}`);
      lines.push("```");
    } else if (analysis.language === "Python") {
      lines.push("```bash");
      lines.push(`pip install ${analysis.name}`);
      lines.push("```");
    } else if (analysis.language === "Rust") {
      lines.push("```bash");
      lines.push(`cargo install ${analysis.name}`);
      lines.push("```");
    } else if (analysis.language === "Go") {
      lines.push("```bash");
      lines.push(`go install ${analysis.entryPoints[0] || analysis.name}@latest`);
      lines.push("```");
    } else if (analysis.language === "Swift") {
      lines.push("```swift");
      lines.push(`// In Package.swift dependencies:`);
      lines.push(`.package(url: "https://github.com/${analysis.name}", from: "1.0.0")`);
      lines.push("```");
    } else if (analysis.language === "C" || analysis.language === "C++") {
      lines.push("```bash");
      lines.push("mkdir build && cd build");
      lines.push("cmake ..");
      lines.push("make");
      lines.push("```");
    } else if (analysis.language === "PHP") {
      lines.push("```bash");
      lines.push(`composer require ${analysis.name}`);
      lines.push("```");
    } else if (analysis.language === "Elixir") {
      lines.push("```elixir");
      lines.push(`# In mix.exs deps:`);
      lines.push(`{:${analysis.name}, "~> 0.1.0"}`);
      lines.push("```");
    }
    lines.push("");
  }

  // Basic usage examples
  if (analysis.usageExamples.length > 0) {
    lines.push("### Basic Usage");
    lines.push("");
    // Show up to 3 code examples, track them for dedup
    const usedBlocks = new Set<string>();
    for (const example of analysis.usageExamples.slice(0, 3)) {
      usedBlocks.add(example);
      lines.push(example);
      lines.push("");
    }

    // Store for later dedup in Examples section
    (analysis as any)._usedCodeBlocks = usedBlocks;
  } else if (analysis.usageSection) {
    lines.push("### Basic Usage");
    lines.push("");
    lines.push(trimSection(analysis.usageSection, 30));
    lines.push("");
  }

  // CLI Commands
  if (isCLI && analysis.cliCommands.length > 0) {
    lines.push("## CLI Commands");
    lines.push("");
    for (const cmd of analysis.cliCommands) {
      lines.push(`- \`${cmd.name}\`${cmd.description ? ` — ${cmd.description}` : ""}`);
    }
    lines.push("");
  }

  // Features (top 5)
  if (analysis.features.length > 0) {
    lines.push("## Key Features");
    lines.push("");
    for (const feat of analysis.features.slice(0, 5)) {
      lines.push(`- ${feat}`);
    }
    lines.push("");
  }

  // Configuration
  if (analysis.configSection) {
    const configBlocks = extractCodeBlocks(analysis.configSection);
    if (configBlocks.length > 0) {
      lines.push("## Configuration");
      lines.push("");
      lines.push(...configBlocks.slice(0, 2));
      lines.push("");
    }
  }

  // Monorepo info
  if (analysis.isMonorepo && analysis.monorepoPackages.length > 0) {
    lines.push("## Packages");
    lines.push("");
    lines.push("This is a monorepo containing the following packages:");
    lines.push("");
    for (const pkg of analysis.monorepoPackages.slice(0, 10)) {
      lines.push(`- \`${pkg}\``);
    }
    if (analysis.monorepoPackages.length > 10) {
      lines.push(`- ... and ${analysis.monorepoPackages.length - 10} more`);
    }
    lines.push("");
  }

  // Examples section (if separate from usage, with dedup)
  if (analysis.examplesSection && analysis.examplesSection !== analysis.usageSection) {
    const usedBlocks: Set<string> = (analysis as any)._usedCodeBlocks || new Set();
    // Remove code blocks that were already shown in Quick Start
    let dedupedExamples = analysis.examplesSection;
    for (const block of usedBlocks) {
      dedupedExamples = dedupedExamples.replace(block, "");
    }
    dedupedExamples = dedupedExamples.replace(/\n{3,}/g, "\n\n").trim();
    if (dedupedExamples.length > 20) {
      lines.push("## Examples");
      lines.push("");
      lines.push(trimSection(dedupedExamples, 40));
      lines.push("");
    }
  }

  // API (brief, point to references)
  if (analysis.apiSection) {
    lines.push("## API");
    lines.push("");
    if (analysis.apiSection.length > 500) {
      lines.push(trimSection(analysis.apiSection, 30));
      lines.push("");
      lines.push("> Full API reference: see `references/api.md`");
    } else {
      lines.push(trimSection(analysis.apiSection, 40));
    }
    lines.push("");
  }

  // Key API
  if (analysis.keyApi.length > 0) {
    lines.push("## Key API");
    lines.push("");
    for (const api of analysis.keyApi) {
      lines.push(`- \`${api}\``);
    }
    lines.push("");
  }

  // Docker info
  if (analysis.dockerInfo) {
    lines.push("## Docker");
    lines.push("");
    lines.push(`- **Base image:** \`${analysis.dockerInfo.baseImage}\``);
    if (analysis.dockerInfo.exposedPorts.length > 0) {
      lines.push(`- **Exposed ports:** ${analysis.dockerInfo.exposedPorts.map(p => `\`${p}\``).join(", ")}`);
    }
    if (analysis.dockerInfo.entrypoint) {
      lines.push(`- **Entrypoint:** \`${analysis.dockerInfo.entrypoint}\``);
    }
    lines.push("");
  }

  // Project Info
  lines.push("## Project Info");
  lines.push("");
  lines.push(`- **Language:** ${analysis.languages.join(", ") || "Unknown"}`);
  if (analysis.license) lines.push(`- **License:** ${analysis.license}`);
  if (analysis.hasTests) lines.push("- **Tests:** Yes");
  if (analysis.dependencies.length > 0) {
    lines.push(`- **Key dependencies:** ${analysis.dependencies.slice(0, 8).join(", ")}`);
  }
  lines.push("");

  // File Structure
  if (analysis.fileTree) {
    lines.push("## File Structure");
    lines.push("");
    lines.push("```");
    lines.push(analysis.fileTree.split("\n").slice(0, 20).join("\n"));
    lines.push("```");
  }

  return ensureClosedCodeBlocks(lines.join("\n"));
}

/**
 * Ensure all fenced code blocks are properly closed.
 */
function ensureClosedCodeBlocks(markdown: string): string {
  let inBlock = false;
  for (const line of markdown.split("\n")) {
    if (/^```/.test(line.trim())) {
      inBlock = !inBlock;
    }
  }
  if (inBlock) {
    return markdown + "\n```";
  }
  return markdown;
}

function extractCodeBlocks(text: string): string[] {
  if (!text) return [];
  const blocks: string[] = [];
  const regex = /```[\s\S]*?```/g;
  let match;
  while ((match = regex.exec(text)) !== null) {
    blocks.push(match[0]);
  }
  return blocks;
}

function trimSection(text: string, maxLines: number): string {
  const lines = text.split("\n").slice(0, maxLines);
  return lines.join("\n");
}
