import * as path from "path";
import * as fs from "fs";
import { RepoAnalysis } from "./analyzer";
import { Repo2SkillResult } from "./index";

export interface SkillQualityDetail {
  label: string;
  score: number;
  maxScore: number;
  pass: boolean;
}

export interface SkillQuality {
  score: number;
  maxScore: number;
  details: SkillQualityDetail[];
  /** Legacy 1-5 score for backward compat */
  legacyScore: number;
}

export function scoreSkillQuality(analysis: RepoAnalysis): SkillQuality {
  const details: SkillQualityDetail[] = [
    {
      label: "Has description",
      score: (analysis.richDescription || analysis.description) ? 10 : 0,
      maxScore: 10,
      pass: !!(analysis.richDescription || analysis.description),
    },
    {
      label: "Has install command",
      score: analysis.installInstructions ? 10 : 0,
      maxScore: 10,
      pass: !!analysis.installInstructions,
    },
    {
      label: "Has examples",
      score: analysis.usageExamples.length >= 3 ? 15 : analysis.usageExamples.length >= 1 ? 10 : analysis.usageSection ? 5 : 0,
      maxScore: 15,
      pass: analysis.usageExamples.length > 0 || !!analysis.usageSection,
    },
    {
      label: "Has features list",
      score: analysis.features.length >= 3 ? 10 : analysis.features.length >= 1 ? 5 : 0,
      maxScore: 10,
      pass: analysis.features.length > 0,
    },
    {
      label: "Has API reference",
      score: analysis.apiSection ? (analysis.keyApi.length > 0 ? 15 : 10) : analysis.keyApi.length > 0 ? 8 : 0,
      maxScore: 15,
      pass: !!(analysis.apiSection || analysis.keyApi.length > 0),
    },
    {
      label: 'Has "When to Use"',
      score: analysis.whenToUse.length > 0 ? 10 : 0,
      maxScore: 10,
      pass: analysis.whenToUse.length > 0,
    },
    {
      label: 'Has "When NOT to Use"',
      score: analysis.whenNotToUse.length > 0 ? 10 : 0,
      maxScore: 10,
      pass: analysis.whenNotToUse.length > 0,
    },
    {
      label: "Has category",
      score: 10, // always detected
      maxScore: 10,
      pass: true,
    },
    {
      label: "Has test examples",
      score: analysis.hasTests ? 10 : 0,
      maxScore: 10,
      pass: analysis.hasTests,
    },
  ];

  const score = details.reduce((sum, d) => sum + d.score, 0);
  const maxScore = details.reduce((sum, d) => sum + d.maxScore, 0);
  const legacyScore = Math.round((score / maxScore) * 5);

  return { score, maxScore, details, legacyScore };
}

export function formatQualityScore(quality: SkillQuality): string {
  const lines: string[] = [];
  lines.push(`📊 Skill Quality Score: ${quality.score}/${quality.maxScore}`);
  for (const d of quality.details) {
    const icon = d.pass ? "✓" : "✗";
    const label = d.pass ? d.label : `Missing ${d.label.replace(/^Has /, "").toLowerCase()}`;
    lines.push(`  ${icon} ${label} (${d.score}/${d.maxScore})`);
  }
  return lines.join("\n");
}

export function generateSkill(
  analysis: RepoAnalysis,
  skillDir: string,
  skillName: string,
  sourceRepo?: string
): Repo2SkillResult {
  fs.mkdirSync(skillDir, { recursive: true });

  const isCLI = analysis.cliCommands.length > 0;
  const description = buildDescription(analysis, isCLI);
  const body = buildBody(analysis, skillName, isCLI);
  const generatedAt = new Date().toISOString();
  const repoLine = sourceRepo ? `\nsource_repo: ${sourceRepo}` : "";

  const skillMd = `---
name: ${skillName}
description: ${description}${repoLine}
generated_at: "${generatedAt}"
---

${body}

> Generated by [repo2skill](https://github.com/NeuZhou/repo2skill)`;

  fs.writeFileSync(path.join(skillDir, "SKILL.md"), skillMd);

  // References
  let referencesCount = 0;
  const refsDir = path.join(skillDir, "references");

  // API reference
  if (analysis.apiSection && analysis.apiSection.length > 200) {
    fs.mkdirSync(refsDir, { recursive: true });
    fs.writeFileSync(path.join(refsDir, "api.md"), `# API Reference — ${skillName}\n\n${analysis.apiSection}`);
    referencesCount++;
  }

  // Full README as reference
  if (analysis.readmeRaw.length > 1000) {
    fs.mkdirSync(refsDir, { recursive: true });
    fs.writeFileSync(path.join(refsDir, "README.md"), analysis.readmeRaw);
    referencesCount++;
  }

  return { skillDir, referencesCount };
}

export interface SkillStructuredData {
  name: string;
  description: string;
  language: string;
  languages: string[];
  category: string;
  features: string[];
  whenToUse: string[];
  whenNotToUse: string[];
  cliCommands: string[];
  installCommand: string;
  packageName: string;
  license: string;
  hasTests: boolean;
  isMonorepo: boolean;
  monorepoPackages: string[];
  dependencies: string[];
  keyApi: string[];
  usageExamples: string[];
  quality: { score: number; maxScore: number };
}

export function buildStructuredData(analysis: RepoAnalysis, category: string): SkillStructuredData {
  const quality = scoreSkillQuality(analysis);
  return {
    name: analysis.name,
    description: analysis.richDescription || analysis.description,
    language: analysis.language,
    languages: analysis.languages,
    category,
    features: analysis.features,
    whenToUse: analysis.whenToUse,
    whenNotToUse: analysis.whenNotToUse,
    cliCommands: analysis.cliCommands.map(c => c.name),
    installCommand: analysis.installInstructions || "",
    packageName: analysis.packageName || analysis.name,
    license: analysis.license,
    hasTests: analysis.hasTests,
    isMonorepo: analysis.isMonorepo,
    monorepoPackages: analysis.monorepoPackages,
    dependencies: analysis.dependencies,
    keyApi: analysis.keyApi,
    usageExamples: analysis.usageExamples,
    quality: { score: quality.score, maxScore: quality.maxScore },
  };
}

function buildDescription(analysis: RepoAnalysis, isCLI: boolean): string {
  const parts: string[] = [];

  const desc = analysis.richDescription || analysis.description || `${analysis.name} — a ${analysis.language} project.`;
  parts.push(desc.split("\n")[0].replace(/\n/g, " ").trim());

  if (analysis.whenToUse.length > 0) {
    parts.push(`WHEN: ${analysis.whenToUse.slice(0, 4).join(", ").toLowerCase()}.`);
  }

  if (analysis.triggerPhrases.length > 0) {
    parts.push(`Triggers: ${analysis.triggerPhrases.slice(0, 4).join(", ")}.`);
  }

  const full = parts.join(" ").replace(/"/g, '\\"');
  return full.slice(0, 200);
}

function buildBody(analysis: RepoAnalysis, skillName: string, isCLI: boolean): string {
  const lines: string[] = [];

  lines.push(`# ${skillName}`);
  lines.push("");

  if (analysis.richDescription) {
    lines.push(analysis.richDescription.split("\n")[0]);
    lines.push("");
  } else if (analysis.description) {
    lines.push(analysis.description.split("\n")[0]);
    lines.push("");
  }

  lines.push("## When to Use");
  lines.push("");
  if (analysis.whenToUse.length > 0) {
    for (const item of analysis.whenToUse) {
      lines.push(`- ${item}`);
    }
  } else if (isCLI) {
    lines.push(`- Run \`${analysis.cliCommands[0]?.name || skillName}\` commands`);
  } else {
    lines.push(`- Work with the ${skillName} ${analysis.language} library`);
  }
  lines.push("");

  if (analysis.whenNotToUse.length > 0) {
    lines.push("## When NOT to Use");
    lines.push("");
    for (const item of analysis.whenNotToUse) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  lines.push("## Quick Start");
  lines.push("");

  if (analysis.installInstructions) {
    const codeBlocks = extractCodeBlocks(analysis.installInstructions);
    if (codeBlocks.length > 0) {
      lines.push("### Install");
      lines.push("");
      lines.push(...codeBlocks.slice(0, 2).map(b => b));
      lines.push("");
    } else {
      lines.push("### Install");
      lines.push("");
      lines.push(trimSection(analysis.installInstructions, 10));
      lines.push("");
    }
  } else {
    lines.push("### Install");
    lines.push("");
    const pkgName = analysis.packageName || analysis.name;
    if (analysis.language === "JavaScript" || analysis.language === "TypeScript") {
      lines.push("```bash");
      lines.push(`npm install ${pkgName}`);
      lines.push("```");
    } else if (analysis.language === "Python") {
      lines.push("```bash");
      lines.push(`pip install ${pkgName}`);
      lines.push("```");
    } else if (analysis.language === "Rust") {
      lines.push("```bash");
      lines.push(`cargo install ${pkgName}`);
      lines.push("```");
    } else if (analysis.language === "Go") {
      lines.push("```bash");
      lines.push(`go install ${analysis.entryPoints[0] || analysis.name}@latest`);
      lines.push("```");
    } else if (analysis.language === "Swift") {
      lines.push("```swift");
      lines.push(`// In Package.swift dependencies:`);
      lines.push(`.package(url: "https://github.com/${analysis.name}", from: "1.0.0")`);
      lines.push("```");
    } else if (analysis.language === "C" || analysis.language === "C++") {
      lines.push("```bash");
      lines.push("mkdir build && cd build");
      lines.push("cmake ..");
      lines.push("make");
      lines.push("```");
    } else if (analysis.language === "PHP") {
      lines.push("```bash");
      lines.push(`composer require ${analysis.name}`);
      lines.push("```");
    } else if (analysis.language === "Elixir") {
      lines.push("```elixir");
      lines.push(`# In mix.exs deps:`);
      lines.push(`{:${analysis.name}, "~> 0.1.0"}`);
      lines.push("```");
    }
    lines.push("");
  }

  if (analysis.usageExamples.length > 0) {
    lines.push("### Basic Usage");
    lines.push("");
    const usedBlocks = new Set<string>();
    for (const example of analysis.usageExamples.slice(0, 3)) {
      usedBlocks.add(example);
      lines.push(example);
      lines.push("");
    }
    (analysis as any)._usedCodeBlocks = usedBlocks;
  } else if (analysis.usageSection) {
    lines.push("### Basic Usage");
    lines.push("");
    lines.push(trimSection(analysis.usageSection, 30));
    lines.push("");
  }

  if (isCLI && analysis.cliCommands.length > 0) {
    lines.push("## CLI Commands");
    lines.push("");
    for (const cmd of analysis.cliCommands) {
      lines.push(`- \`${cmd.name}\`${cmd.description ? ` — ${cmd.description}` : ""}`);
    }
    lines.push("");
  }

  if (analysis.features.length > 0) {
    lines.push("## Key Features");
    lines.push("");
    for (const feat of analysis.features.slice(0, 5)) {
      lines.push(`- ${feat}`);
    }
    lines.push("");
  }

  if (analysis.configSection) {
    const configBlocks = extractCodeBlocks(analysis.configSection);
    if (configBlocks.length > 0) {
      lines.push("## Configuration");
      lines.push("");
      lines.push(...configBlocks.slice(0, 2));
      lines.push("");
    }
  }

  if (analysis.isMonorepo && analysis.monorepoPackages.length > 0) {
    lines.push("## Packages");
    lines.push("");
    lines.push("This is a monorepo containing the following packages:");
    lines.push("");
    for (const pkg of analysis.monorepoPackages.slice(0, 10)) {
      lines.push(`- \`${pkg}\``);
    }
    if (analysis.monorepoPackages.length > 10) {
      lines.push(`- ... and ${analysis.monorepoPackages.length - 10} more`);
    }
    lines.push("");
  }

  if (analysis.examplesSection && analysis.examplesSection !== analysis.usageSection) {
    const usedBlocks: Set<string> = (analysis as any)._usedCodeBlocks || new Set();
    let dedupedExamples = analysis.examplesSection;
    for (const block of usedBlocks) {
      dedupedExamples = dedupedExamples.replace(block, "");
    }
    dedupedExamples = dedupedExamples.replace(/\n{3,}/g, "\n\n").trim();
    if (dedupedExamples.length > 20) {
      lines.push("## Examples");
      lines.push("");
      lines.push(trimSection(dedupedExamples, 40));
      lines.push("");
    }
  }

  if (analysis.apiSection) {
    lines.push("## API");
    lines.push("");
    if (analysis.apiSection.length > 500) {
      lines.push(trimSection(analysis.apiSection, 30));
      lines.push("");
      lines.push("> Full API reference: see `references/api.md`");
    } else {
      lines.push(trimSection(analysis.apiSection, 40));
    }
    lines.push("");
  }

  if (analysis.keyApi.length > 0) {
    lines.push("## Key API");
    lines.push("");
    for (const api of analysis.keyApi) {
      lines.push(`- \`${api}\``);
    }
    lines.push("");
  }

  if (analysis.dockerInfo) {
    lines.push("## Docker");
    lines.push("");
    lines.push(`- **Base image:** \`${analysis.dockerInfo.baseImage}\``);
    if (analysis.dockerInfo.exposedPorts.length > 0) {
      lines.push(`- **Exposed ports:** ${analysis.dockerInfo.exposedPorts.map(p => `\`${p}\``).join(", ")}`);
    }
    if (analysis.dockerInfo.entrypoint) {
      lines.push(`- **Entrypoint:** \`${analysis.dockerInfo.entrypoint}\``);
    }
    lines.push("");
  }

  lines.push("## Project Info");
  lines.push("");
  lines.push(`- **Language:** ${analysis.languages.join(", ") || "Unknown"}`);
  if (analysis.license) lines.push(`- **License:** ${analysis.license}`);
  if (analysis.hasTests) lines.push("- **Tests:** Yes");
  if (analysis.dependencies.length > 0) {
    lines.push(`- **Key dependencies:** ${analysis.dependencies.slice(0, 8).join(", ")}`);
  }
  lines.push("");

  if (analysis.fileTree) {
    lines.push("## File Structure");
    lines.push("");
    lines.push("```");
    lines.push(analysis.fileTree.split("\n").slice(0, 20).join("\n"));
    lines.push("```");
  }

  return ensureClosedCodeBlocks(lines.join("\n"));
}

function ensureClosedCodeBlocks(markdown: string): string {
  let inBlock = false;
  for (const line of markdown.split("\n")) {
    if (/^```/.test(line.trim())) {
      inBlock = !inBlock;
    }
  }
  if (inBlock) {
    return markdown + "\n```";
  }
  return markdown;
}

function extractCodeBlocks(text: string): string[] {
  if (!text) return [];
  const blocks: string[] = [];
  const regex = /```[\s\S]*?```/g;
  let match;
  while ((match = regex.exec(text)) !== null) {
    blocks.push(match[0]);
  }
  return blocks;
}

function trimSection(text: string, maxLines: number): string {
  const lines = text.split("\n").slice(0, maxLines);
  return lines.join("\n");
}
