/**
 * Plugin System — allow custom analyzers for repo2skill.
 */

import * as fs from "fs";
import * as path from "path";
import { RepoAnalysis } from "./analyzer";

export interface SkillSection {
  heading: string;
  content: string;
  /** Priority: higher = placed earlier in SKILL.md */
  priority?: number;
}

export interface RepoData {
  /** Absolute path to the repo root */
  repoDir: string;
  /** Analysis result from the built-in analyzer */
  analysis: RepoAnalysis;
  /** Read a file from the repo, returns content or null if not found */
  readFile(relativePath: string): string | null;
  /** List files matching a glob-like pattern */
  listFiles(pattern?: string): string[];
}

export interface RepoSkillPlugin {
  /** Unique plugin name */
  name: string;
  /** Optional description */
  description?: string;
  /** Optional: return true if this plugin should run for this repo */
  shouldActivate?(repo: RepoData): boolean;
  /** Produce additional skill sections */
  analyze(repo: RepoData): SkillSection[];
}

/**
 * Create a RepoData wrapper for a directory + analysis.
 */
export function createRepoData(repoDir: string, analysis: RepoAnalysis): RepoData {
  return {
    repoDir,
    analysis,
    readFile(relativePath: string): string | null {
      const fullPath = path.join(repoDir, relativePath);
      try {
        return fs.readFileSync(fullPath, "utf-8");
      } catch {
        return null;
      }
    },
    listFiles(pattern?: string): string[] {
      const files: string[] = [];
      function walk(dir: string, rel: string) {
        const entries = fs.readdirSync(dir, { withFileTypes: true });
        for (const entry of entries) {
          if (entry.name === "node_modules" || entry.name === ".git") continue;
          const relPath = rel ? `${rel}/${entry.name}` : entry.name;
          if (entry.isDirectory()) {
            walk(path.join(dir, entry.name), relPath);
          } else {
            files.push(relPath);
          }
        }
      }
      walk(repoDir, "");
      if (!pattern) return files;
      const regex = new RegExp(pattern.replace(/\*/g, ".*").replace(/\?/g, "."), "i");
      return files.filter(f => regex.test(f));
    },
  };
}

/**
 * Load a plugin from a file path. Supports .ts (requires ts-node/tsx) and .js files.
 */
export async function loadPlugin(pluginPath: string): Promise<RepoSkillPlugin> {
  const absPath = path.resolve(pluginPath);
  if (!fs.existsSync(absPath)) {
    throw new Error(`Plugin file not found: ${absPath}`);
  }

  let plugin: any;
  try {
    // For .ts files, try require with ts-node or tsx
    plugin = require(absPath);
  } catch (err: any) {
    // Try dynamic import as fallback
    try {
      plugin = await import(absPath);
    } catch {
      throw new Error(`Failed to load plugin from ${absPath}: ${err.message}`);
    }
  }

  // Handle default exports
  const resolved = plugin.default || plugin;

  if (!resolved.name || typeof resolved.analyze !== "function") {
    throw new Error(`Invalid plugin: must export { name: string, analyze: (repo) => SkillSection[] }`);
  }

  return resolved as RepoSkillPlugin;
}

/**
 * Run plugins on a repo and collect their sections.
 */
export function runPlugins(plugins: RepoSkillPlugin[], repoData: RepoData): SkillSection[] {
  const sections: SkillSection[] = [];

  for (const plugin of plugins) {
    if (plugin.shouldActivate && !plugin.shouldActivate(repoData)) {
      continue;
    }

    try {
      const result = plugin.analyze(repoData);
      if (Array.isArray(result)) {
        sections.push(...result);
      }
    } catch (err: any) {
      console.warn(`⚠️  Plugin "${plugin.name}" failed: ${err.message}`);
    }
  }

  // Sort by priority (higher first)
  sections.sort((a, b) => (b.priority || 0) - (a.priority || 0));

  return sections;
}

/**
 * Inject plugin sections into SKILL.md content (before the "Generated by" footer).
 */
export function injectPluginSections(skillMdContent: string, sections: SkillSection[]): string {
  if (sections.length === 0) return skillMdContent;

  const pluginContent = sections
    .map(s => `## ${s.heading}\n\n${s.content}`)
    .join("\n\n");

  const footerIdx = skillMdContent.lastIndexOf("> Generated by");
  if (footerIdx !== -1) {
    return skillMdContent.slice(0, footerIdx) + pluginContent + "\n\n" + skillMdContent.slice(footerIdx);
  }

  return skillMdContent + "\n\n" + pluginContent;
}
