/**
 * Skill Versioning — track and pin skill versions to specific repo tags/commits.
 */

import * as path from "path";
import * as fs from "fs";
import simpleGit from "simple-git";

export interface VersionInfo {
  tag?: string;
  commit: string;
  commitShort: string;
  date: string;
  message?: string;
}

/**
 * Get version info from a git repo directory.
 */
export async function getVersionInfo(repoDir: string, tag?: string): Promise<VersionInfo> {
  const git = simpleGit(repoDir);

  if (tag) {
    // Checkout specific tag
    try {
      await git.checkout(tag);
    } catch (err: any) {
      throw new Error(`Tag "${tag}" not found in repository. Use \`git tag\` to list available tags.`);
    }
  }

  const log = await git.log({ maxCount: 1 });
  const latest = log.latest;
  if (!latest) {
    throw new Error("No commits found in repository.");
  }

  return {
    tag: tag || undefined,
    commit: latest.hash,
    commitShort: latest.hash.slice(0, 7),
    date: latest.date,
    message: latest.message,
  };
}

/**
 * Generate version stamp for SKILL.md frontmatter.
 */
export function generateVersionStamp(info: VersionInfo): string {
  const parts: string[] = [];
  if (info.tag) {
    parts.push(`version_tag: "${info.tag}"`);
  }
  parts.push(`version_commit: "${info.commitShort}"`);
  parts.push(`version_date: "${info.date}"`);
  return parts.join("\n");
}

/**
 * Generate human-readable version line for SKILL.md body.
 */
export function formatVersionLine(info: VersionInfo): string {
  if (info.tag) {
    return `> This skill was generated from ${info.tag} (commit ${info.commitShort})`;
  }
  return `> This skill was generated from commit ${info.commitShort} (${info.date})`;
}

/**
 * Inject version info into an existing SKILL.md content.
 */
export function injectVersionInfo(skillMdContent: string, info: VersionInfo): string {
  let content = skillMdContent;

  // Inject into frontmatter
  const frontmatterMatch = content.match(/^(---\n)([\s\S]*?)(\n---)/);
  if (frontmatterMatch) {
    const stamp = generateVersionStamp(info);
    // Remove old version fields
    let frontmatter = frontmatterMatch[2]
      .replace(/^version_tag:.*\n?/m, "")
      .replace(/^version_commit:.*\n?/m, "")
      .replace(/^version_date:.*\n?/m, "")
      .trimEnd();
    frontmatter += "\n" + stamp;
    content = frontmatterMatch[1] + frontmatter + frontmatterMatch[3] + content.slice(frontmatterMatch[0].length);
  }

  // Add/replace version line before "Generated by" footer
  const versionLine = formatVersionLine(info);
  const generatedByIdx = content.indexOf("> Generated by");
  if (generatedByIdx !== -1) {
    // Remove existing version line if present
    content = content.replace(/^> This skill was generated from .+\n?/m, "");
    // Insert before "Generated by"
    const beforeGenerated = content.slice(0, content.indexOf("> Generated by"));
    const afterGenerated = content.slice(content.indexOf("> Generated by"));
    content = beforeGenerated.trimEnd() + "\n\n" + versionLine + "\n\n" + afterGenerated;
  } else {
    content = content.trimEnd() + "\n\n" + versionLine;
  }

  return content;
}

/**
 * List available tags from a git repo.
 */
export async function listTags(repoDir: string): Promise<string[]> {
  const git = simpleGit(repoDir);
  const result = await git.tags();
  return result.all;
}

export interface VersionHistoryEntry {
  version: string;
  date: string;
  commit: string;
  summary: string;
}

/**
 * Extract version history from a SKILL.md file's frontmatter comments.
 * Looks for <!-- version_history: [...] --> blocks.
 */
export function extractVersionHistory(content: string): VersionHistoryEntry[] {
  const match = content.match(/<!--\s*version_history:\s*(\[[\s\S]*?\])\s*-->/);
  if (!match) return [];
  try {
    return JSON.parse(match[1]);
  } catch {
    return [];
  }
}

/**
 * Add a version entry to SKILL.md content.
 */
export function addVersionEntry(
  content: string,
  entry: VersionHistoryEntry,
): string {
  const history = extractVersionHistory(content);
  history.unshift(entry);

  const historyBlock = `<!-- version_history: ${JSON.stringify(history)} -->`;

  // Replace existing block or append before footer
  const existingMatch = content.match(/<!--\s*version_history:[\s\S]*?-->/);
  if (existingMatch) {
    return content.replace(existingMatch[0], historyBlock);
  }

  // Insert before "Generated by" footer or at end
  const generatedIdx = content.indexOf("> Generated by");
  if (generatedIdx !== -1) {
    return content.slice(0, generatedIdx).trimEnd() + "\n\n" + historyBlock + "\n\n" + content.slice(generatedIdx);
  }
  return content.trimEnd() + "\n\n" + historyBlock + "\n";
}

/**
 * Format version history for CLI display.
 */
export function formatVersionHistory(current: VersionInfo | null, history: VersionHistoryEntry[]): string {
  const lines: string[] = [];
  if (current) {
    lines.push(`Current: ${current.tag || `commit ${current.commitShort}`} (${current.date})`);
  }
  if (history.length > 0) {
    lines.push("History:");
    for (const entry of history) {
      lines.push(`  ${entry.version} - ${entry.date} - ${entry.summary}`);
    }
  } else {
    lines.push("No version history recorded.");
  }
  return lines.join("\n");
}
